Importing Libraries

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

Load The Data Set

In [2]:
data=pd.read_csv("delivery_time.csv")
data.head()

Delivery Time  Sorting Time
0          21.00            10
1          13.50             4
2          19.75             6
3          24.00             9
4          29.00            10

Some information about the dataset

In [3]:
data.shape

(21, 2)

In [4]:
data.columns

Index(['Delivery Time', 'Sorting Time'], dtype='object')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Delivery Time  21 non-null     float64
 1   Sorting Time   21 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 468.0 bytes


In [6]:
data.describe()

Delivery Time  Sorting Time
count      21.000000     21.000000
mean       16.790952      6.190476
std         5.074901      2.542028
min         8.000000      2.000000
25%        13.500000      4.000000
50%        17.830000      6.000000
75%        19.750000      8.000000
max        29.000000     10.000000

Check the null values in the dataset

No null values in the dataset

In [7]:
data.isnull().sum()

Delivery Time    0
Sorting Time     0
dtype: int64

 Spliting the dataset ino Feature and Target

In [8]:
x = data["Sorting Time"].values.reshape(-1,1)
y = data["Delivery Time"].values.reshape(-1,1)

In [9]:
print(x)

[[10]
 [ 4]
 [ 6]
 [ 9]
 [10]
 [ 6]
 [ 7]
 [ 3]
 [10]
 [ 9]
 [ 8]
 [ 4]
 [ 7]
 [ 3]
 [ 3]
 [ 4]
 [ 6]
 [ 7]
 [ 2]
 [ 7]
 [ 5]]


In [10]:
print(y)

[[21.  ]
 [13.5 ]
 [19.75]
 [24.  ]
 [29.  ]
 [15.35]
 [19.  ]
 [ 9.5 ]
 [17.9 ]
 [18.75]
 [19.83]
 [10.75]
 [16.68]
 [11.5 ]
 [12.03]
 [14.88]
 [13.75]
 [18.11]
 [ 8.  ]
 [17.83]
 [21.5 ]]


In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
print(data.std())

Delivery Time    5.074901
Sorting Time     2.542028
dtype: float64


In [13]:
scaler = StandardScaler()

In [14]:
scaler.fit(x)

StandardScaler()

In [15]:
x_standerdized = scaler.transform(x)

In [16]:
print(x_standerdized)

[[ 1.53562462]
 [-0.88298415]
 [-0.07678123]
 [ 1.13252315]
 [ 1.53562462]
 [-0.07678123]
 [ 0.32632023]
 [-1.28608562]
 [ 1.53562462]
 [ 1.13252315]
 [ 0.72942169]
 [-0.88298415]
 [ 0.32632023]
 [-1.28608562]
 [-1.28608562]
 [-0.88298415]
 [-0.07678123]
 [ 0.32632023]
 [-1.68918708]
 [ 0.32632023]
 [-0.47988269]]


In [17]:
print(x_standerdized.std())

1.0


In [18]:
y_standerdized = scaler.transform(y)

In [19]:
print(y_standerdized)

[[5.9697407 ]
 [2.94647973]
 [5.46586387]
 [7.17904508]
 [9.19455239]
 [3.69221744]
 [5.16353777]
 [1.33407389]
 [4.72012616]
 [5.06276241]
 [5.49811199]
 [1.83795071]
 [4.22834238]
 [2.14027681]
 [2.35392058]
 [3.50275975]
 [3.0472551 ]
 [4.80477747]
 [0.72942169]
 [4.69190906]
 [6.17129143]]


In [20]:
print(y_standerdized.std())

1.996398747428103


In [21]:
model = LinearRegression()
print("Load The Model")

Load The Model


In [22]:
model_train = model.fit(x_standerdized,y_standerdized)
print("Model is Trained")

Model is Trained


In [23]:
pred = model_train.predict(x_standerdized)
print("Model is Predict")

Model is Predict


In [24]:
print(pred)

[[6.80534299]
 [2.81700901]
 [4.14645367]
 [6.14062066]
 [6.80534299]
 [4.14645367]
 [4.811176  ]
 [2.15228668]
 [6.80534299]
 [6.14062066]
 [5.47589833]
 [2.81700901]
 [4.811176  ]
 [2.15228668]
 [2.15228668]
 [2.81700901]
 [4.14645367]
 [4.811176  ]
 [1.48756435]
 [4.811176  ]
 [3.48173134]]


In [25]:
{"Actual":y_standerdized,"predict":x_standerdized}

{'Actual': array([[5.9697407 ],
        [2.94647973],
        [5.46586387],
        [7.17904508],
        [9.19455239],
        [3.69221744],
        [5.16353777],
        [1.33407389],
        [4.72012616],
        [5.06276241],
        [5.49811199],
        [1.83795071],
        [4.22834238],
        [2.14027681],
        [2.35392058],
        [3.50275975],
        [3.0472551 ],
        [4.80477747],
        [0.72942169],
        [4.69190906],
        [6.17129143]]),
 'predict': array([[ 1.53562462],
        [-0.88298415],
        [-0.07678123],
        [ 1.13252315],
        [ 1.53562462],
        [-0.07678123],
        [ 0.32632023],
        [-1.28608562],
        [ 1.53562462],
        [ 1.13252315],
        [ 0.72942169],
        [-0.88298415],
        [ 0.32632023],
        [-1.28608562],
        [-1.28608562],
        [-0.88298415],
        [-0.07678123],
        [ 0.32632023],
        [-1.68918708],
        [ 0.32632023],
        [-0.47988269]])}

In [26]:
model_acc = r2_score(pred,y_standerdized)

In [27]:
print(model_acc)

0.5343077691589178
